import React from "react";
import "../css/Body.css";
import One from "../assets/One.png";
import Two from "../assets/Two.png";
import Three from "../assets/Three.png";
export default function Body() {
  return (
    <>
      <div className="container mt-4 mb-4">
        <div className="row">
          <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12  d-flex align-items-center justify-content-center">
            <div>
              <img
                className="homeImageLocker img-fluid pos"
                src={One}
                alt=""
              />
            </div>
          </div>
          <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex justify-content-center  flex-column align-items-center mt-5">
            <h1
              className="text-white heroContenth1"
              id=""
              style={{ fontWeight: "bold" }}
            >
              Become an Affiliate
            </h1>
            <p className="mt-4">
              Earn 1% of all fees generated by tokens created with your link.
            </p>
            <button
              className="heroSectionBtn mt-4"
              style={{ fontWeight: "normal", fontSize: "small" }}
            >
              GET YOUR LINK
            </button>
          </div>
        </div>
      </div>
      {/* Section How It Work */}
      <section className=" mt-5 mb-5 ">
        <div className="row">
          <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex justify-content-center  flex-column align-items-center">
            <h1 className="pos bg-transparent" style={{ fontWeight: "bolder" }}>How it Works</h1>
          </div>
          <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 text-center  d-flex justify-content-center  flex-column align-items-center">
            <h3 className= "pos bg-transparent" style={{ fontWeight: "bolder" }}>
              Create your crypto token in under a minute
            </h3>
            <p className="mt-2 text-center" style={{ fontSize: "large" }}>
              Use Coin Genie to deploy your customized Smart Contract on the
              Ethereum blockchain
            </p>
          </div>
        </div>
      </section>
      {/* Steps */}
      <section>
        <div className="container">
          <div className="row ">
            <div className="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 d-flex justify-content-center ">
              <div className="card mb-5" style={{ width: "18rem" }}>
                <center>
                  <img
                    className="card-img-top mt-5 mb-3"
                    src={One}
                    alt="feature 1"
                  />
                </center>
                <div className="card-body pb-5  ">
                  <h5
                    className="card-title fw-bolder text-center cardStep"
                    style={{ fontSize: "large",zIndex:"41" }}
                  >
                    1. Crypto Token Creation{" "}
                  </h5>
                  <p className="card-text" style={{ color: "#7B7B93",zIndex:"41" }}>
                    Enter your crypto token details into a simple form, then
                    click a button. Yes. That is it.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-xs-12 d-flex justify-content-center">
              <div className="card mb-5 " style={{ width: "18rem" }}>
                <center>
                  <img
                    className="card-img-top mt-5 mb-3"
                    src={Two}
                    alt="feature 2"
                  />
                </center>
                <div className="card-body pb-5">
                  <h5
                    className="card-title fw-bolder text-center cardStep"
                    style={{ fontSize: "large " }}
                  >
                    2. Adding Liquidity{" "}
                  </h5>
                  <p className="card-text" style={{ color: "#7B7B93" }}>
                    Make your new crypto token available for trading on Uniswap
                    by adding liquidity on Coin Genie.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-xl-4 col-xxl-4  col-lg-4 col-md-6 col-sm-12 col-xs-12 d-flex justify-content-center  ">
              <div className="card mb-5" style={{ width: "18rem" }}>
                <center>
                  <img
                    className="card-img-top mt-5 mb-3 pos"
                    src={Three}
                    alt="feature 3"
                  />
                </center>
                <div className="card-body pb-5">
                  <h5
                    className="card-title fw-bolder text-center cardStep"
                    style={{ fontSize: "large",zIndex:"41" }}
                  >
                    3. Manage{" "}
                  </h5>
                  <p className="card-text" style={{ color: "#7B7B93",zIndex:"41" }}>
                    We provide all the tools you need. Contract verification,
                    renouncing ownership, and more!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container mt-5 ">
          <div className="row d-flex justify-content-center align-items-center">
            <button
              className="heroSectionBtn mt-4"
              style={{
                fontWeight: "normal",
                fontSize: "small",
                width: "fit-content",
              }}
            >
             DOCUMENTATION
            </button>
            <button
              className="heroSectionBtn mt-4"
              style={{
                fontWeight: "normal",
                fontSize: "small",
                width: "fit-content",
              }}
            >
              VIDEO TUTORIALS
            </button>
          </div>
        </div>
      </section>
      {/* Why US */}
      <section>
        <div className="container mt-4 mb-4">
          <div className="row">
            <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex justify-content-center  flex-column align-items-center mt-5">
              <h1
                className="text-white heroContenth1"
                id=""
                style={{ fontWeight: "bold" }}
              >
                Become an Affiliate
              </h1>
              <p className="mt-4">
                Earn 1% of all fees generated by tokens created with your link.
              </p>
              <button
                className="heroSectionBtn mt-4"
                style={{ fontWeight: "normal", fontSize: "small" }}
              >
                GET YOUR LINK
              </button>
            </div>
            <div className="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12  d-flex align-items-center justify-content-center">
              <div>
                <img
                  className="homeImageLocker img-fluid pos "
                  src={Two}
                  alt=""
                />
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* FAQS */}
      {/*  
      <div className="container mt-5 mb-5 ">
        <div className="row">
          <h1>Frequently Asked Question</h1>
          <h4 className="mt-4 mb-5" style={{ fontWeight: "bold" }}>
            General Questions
          </h4>
          <div className="accordion accordion-flush" id="accordionFlushExample">
            <div className="accordion-item">
              <h2 className="accordion-header" id="flush-headingOne">
                <button
                  className="accordion-button collapsed text-white  bg-transparent"
                  style={{ fontWeight: "bold" }}
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#flush-collapseOne"
                  aria-expanded="false"
                  aria-controls="flush-collapseOne"
                >
                  What is Ethereum Blockchain?
                </button>
              </h2>
              <div
                id="flush-collapseOne"
                className="accordion-collapse collapse"
                aria-labelledby="flush-headingOne"
                data-bs-parent="#accordionFlushExample"
              >
                <div className="accordion-body">
                  Ethereum is a platform based on blockchain technology, which
                  is open-source and facilitates the development and
                  distribution of applications in various domains including
                  business, finance, and entertainment. This blockchain platform
                  is particularly tailored for the development of smart
                  contracts and decentralized applications, commonly known as
                  DApps.
                </div>
              </div>
            </div>
            <br />
            <div className="accordion-item">
              <h2 className="accordion-header" id="flush-headingTwo">
                <button
                  className="accordion-button collapsed text-white  bg-transparent"
                  style={{ fontWeight: "bold" }}
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#flush-collapseTwo"
                  aria-expanded="false"
                  aria-controls="flush-collapseTwo"
                >
                  What is ERC-20 Token?
                </button>
              </h2>
              <div
                id="flush-collapseTwo"
                className="accordion-collapse collapse"
                aria-labelledby="flush-headingTwo"
                data-bs-parent="#accordionFlushExample"
              >
                <div className="accordion-body">
                  ERC-20 tokens represent a type of digital asset on the
                  blockchain. These tokens are essentially Smart Contracts that
                  operate on the Ethereum blockchain network. Similar to other
                  cryptocurrencies, they can be transferred and received. The
                  ERC-20 Standard outlines specific guidelines for the transfer,
                  receipt, and storage of these assets.
                </div>
              </div>
            </div>
            <br />
          </div>
          <h4 className="mt-2 mb-2" style={{ fontWeight: "bold" }}>
            Token Questions
          </h4>
          <div className="accordion accordion-flush" id="accordionFlushExample">
            <div className="accordion-item">
              <h2 className="accordion-header " id="flush-headingFour">
                <button
                  className="accordion-button collapsed text-white bg-transparent fw-bold"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#flush-collapseFour"
                  aria-expanded="false"
                  aria-controls="flush-collapseFour"
                >
                  How do i verify my contract?
                </button>
              </h2>
              <div
                id="flush-collapseFour"
                className="accordion-collapse collapse"
                aria-labelledby="flush-headingFour"
                data-bs-parent="#accordionFlushExample"
              >
                <div className="accordion-body">
                  With Coin Genie, you can verify your contract with the click
                  of a button after you have successfully deployed it. See the
                  documentation or watch the tutorials for more information.
                </div>
              </div>
            </div>
            <br />
            <div className="accordion-item">
              <h2 className="accordion-header" id="flush-headingFive">
                <button
                  className="accordion-button collapsed text-white bg-transparent fw-bold"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#flush-collapseFive"
                  aria-expanded="false"
                  aria-controls="flush-collapseFive"
                >
                  Where is my Token Address?
                </button>
              </h2>
              <div
                id="flush-collapseFive"
                className="accordion-collapse collapse"
                aria-labelledby="flush-headingFive"
                data-bs-parent="#accordionFlushExample"
              >
                <div className="accordion-body">
                  You can view your crypto token address on the Token Details
                  page. You will be able to see your token address after you
                  have successfully deployed your token. You can also view your
                  token details on Etherscan by clicking the address in your
                  Token Details page.
                </div>
              </div>
            </div>
            <br />
            <div className="accordion-item">
              <h2 className="accordion-header" id="flush-headingSix">
                <button
                  className="accordion-button collapsed text-white bg-transparent fw-bold"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#flush-collapseSix"
                  aria-expanded="false"
                  aria-controls="flush-collapseSix"
                >
                  Who will be the token owner?
                </button>
              </h2>
              <div
                id="flush-collapseSix"
                className="accordion-collapse collapse"
                aria-labelledby="flush-headingSix"
                data-bs-parent="#accordionFlushExample"
              >
                <div className="accordion-body">Who will be fee recipient?</div>
              </div>
            </div>
            <br />
            <div className="accordion-item">
              <h2 className="accordion-header" id="flush-headingSeven">
                <button
                  className="accordion-button collapsed text-white bg-transparent fw-bold"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#flush-collapseSeven"
                  aria-expanded="false"
                  aria-controls="flush-collapseSeven"
                >
                  Where will be token supply go after deployment?
                </button>
              </h2>
              <div
                id="flush-collapseSeven"
                className="accordion-collapse collapse "
                aria-labelledby="flush-headingSeven"
                data-bs-parent="#accordionFlushExample"
              >
                <div className="accordion-body">
                  The initial supply of the token is transferred to the address
                  that created the token. This address is also the owner and
                  therefore has special rights to manage the token.
                </div>
              </div>
            </div>
            <br />
          </div>
        </div>
      </div>
    */}
    </>
  );
}
